core/urls.py
from django.urls import path 
from . import views
from django.conf import settings
from django.conf.urls.static import static




app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    
   
  

   
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.contrib import admin
from django.urls import path, include






urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', include('register.urls', namespace='register')),
    path('projects/', include('projects.urls', namespace='projects')),

]

register/urls.py
from django.urls import path
from . import views

app_name = 'register'

urlpatterns = [
    path('new-user/', views.register, name='new-user'),
    path('new-company/', views.newCompany, name='new-company'),
    path('users/', views.usersView, name='users'),
    path('users/profile', views.profile, name='profile'),
    path('users/<int:profile_id>/', views.user_view, name='user'),
    path('users/invite/<int:profile_id>/', views.invite, name='invite'),
    path('users/invites/', views.invites, name='invites'),
    path('users/invites/accept/<int:invite_id>/', views.acceptInvite, name='accept-invite'),
    path('users/invites/delete/<int:invite_id>/', views.deleteInvite, name='delete-invite'),
    path('users/friends/', views.friends, name='friends'),
    path('users/friends/remove/<int:profile_id>/', views.remove_friend, name='remove-friend'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import logout
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.urls import reverse
from django.http import HttpResponseRedirect
from register.models import Company
from register.models import Project
from register.models import UserProfile
from projects.models import Task


# Create your views here.
def index(request):
    return render(request, 'core/index.html')

def dashboard(request):
    users = User.objects.all()
    active_users = User.objects.all().filter(is_active=True)
    companies = Company.objects.all()
    projects = Project.objects.all()
    tasks = Task.objects.all()
    context = {
        'users' : users,
        'active_users' : active_users,
        'companies' : companies,
        'projects' : projects,
        'tasks' : tasks,
    }
    return render(request, 'core/dashboard.html', context)



def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            authenticated_user = authenticate(username=request.POST['username'], password=request.POST['password'])
            login(request, authenticated_user)
            return redirect('core:index')
        else:
            return render(request, 'register/login.html', {'login_form':form})
    else:
        form = AuthenticationForm()
    return render(request, 'register/login.html', {'login_form':form})


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('core:index'))


def context(request): # send context to base.html
    # if not request.session.session_key:
    #     request.session.create()
    users = User.objects.all()
    users_prof = UserProfile.objects.all()
    if request.user.is_authenticated:
        try:
            users_prof = UserProfile.objects.exclude(
                id=request.user.userprofile_set.values_list()[0][0])  # exclude himself from invite list
            user_id = request.user.userprofile_set.values_list()[0][0]
            logged_user = UserProfile.objects.get(id=user_id)
            friends = logged_user.friends.all()
            context = {
                'users': users,
                'users_prof': users_prof,
                'logged_user': logged_user,
                'friends' : friends,
            }
            return context
        except:
            users_prof = UserProfile.objects.all()
            context = {
                'users':users,
                'users_prof':users_prof,
            }
            return context
    else:
        context = {
            'users': users,
            'users_prof': users_prof,
        }
        return context

core/templates/core/dashboard.html
{% extends 'core/base.html' %}
{% load static %}

{% block content %}

<div class="container-fluid">
<div class="animated fadeIn">
  <div class="row">
    <div class="col-sm-12 col-lg-6">
      <div class="card text-white bg-primary rounded">
        <div class="card-body pb-0">
          <h4 class="mb-0">{{ companies.count }}</h4>
          <p>Registered Companies</p>
        </div>
        <div class="chart-wrapper px-3" style="height:70px;"><div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
          <canvas id="card-chart1" class="chart chartjs-render-monitor" height="70" width="248" style="display: block; width: 248px; height: 70px;"></canvas>
        </div>
      </div>
    </div>
    <!--/.col-->

    <div class="col-sm-12 col-lg-6">
      <div class="card text-white bg-info rounded">
        <div class="card-body pb-0">
          <h4 class="mb-0">{{ users.count }}</h4>
          <p>Registered Users</p>
        </div>
        <div class="chart-wrapper px-3" style="height:70px;"><div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
          <canvas id="card-chart2" class="chart chartjs-render-monitor" height="70" width="248" style="display: block; width: 248px; height: 70px;"></canvas>
        </div>
      </div>
    </div>
    <!--/.col-->

    <div class="col-sm-12 col-lg-6">
      <div class="card text-white bg-warning rounded">
        <div class="card-body pb-0">
          <h4 class="mb-0">{{ projects.count }}</h4>
          <p>Projects</p>
        </div>
        <div class="chart-wrapper" style="height:70px;"><div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
          <canvas id="card-chart3" class="chart chartjs-render-monitor" height="70" width="280" style="display: block; width: 280px; height: 70px;"></canvas>
        </div>
      </div>
    </div>
    <!--/.col-->

    <div class="col-sm-12 col-lg-6">
      <div class="card text-white bg-danger rounded">
        <div class="card-body pb-0">
          <h4 class="mb-0">{{ tasks.count }}</h4>
          <p>Tasks</p>
        </div>
        <div class="chart-wrapper px-3" style="height:70px;"><div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
          <canvas id="card-chart4" class="chart chartjs-render-monitor" height="70" width="248" style="display: block; width: 248px; height: 70px;"></canvas>
        </div>
      </div>
    </div>
    <!--/.col-->
  </div>
  <!--/.row-->
</div>

</div>

{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}

{% block breadcrumb %}
<li class="breadcrumb-item active rounded">Home</li>
{% endblock breadcrumb%}

{% block content %}
<div class="container-fluid">
  <div id="ui-view" style="opacity: 1;"><div class="animated fadeIn">
    <div class="row">
    <div class="col-12">
      <div class="card rounded">
      <div class="card-body">
        <div class="jumbotron bg-white">
          <h1 class="display-4">Welcome</h1>
          <p class="lead">Our Incudemist Business Management System.</p>
          <hr class="my-4">
          <p>Register your company and start managing your projects</p>
          <p>That's it, simple, easy, fast.</p>
          <p class="lead">
            <a class="btn btn-primary btn-lg rounded" href="{% url 'register:new-company' %}" role="button">Set up your company</a>
          </p>
          {% if not user.is_authenticated %}
          <a href="{% url 'core:login' %}">Click here if you are already registered</a>
          {% endif %}
        </div>
      </div>
      </div>
    </div>
    </div>
    </div>
  </div>
</div>

{% endblock %}

core/templates/core/login-page.html
{% load static%}
<!doctype html>
<html lang="en">
<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.9/css/all.css" integrity="sha384-5SOiIsAziJl6AWe0HWRKTXlfcSHKmYV4RBF18PPJ173Kzn7jzMyFuTtk8JA7QQG1" crossorigin="anonymous">

 <!--Main CSS-->   
 
 <link rel="stylesheet" href="{% static 'core/css/login.css' %}">
 



<title>Login</title>
<link rel="shortcut icon" href="{% static 'core/img/logos/logo4.svg' %}">
</head>
<body>
    
    {% block body %}

    <div class="d-lg-flex half">
        <div class="bg order-1 order-md-2" style="overflow: hidden;"><img src="https://picsum.photos/id/0/1000/955">
        </div>
    <div class="contents order-2 order-md-1">
    <div class="container">
    <div class="row align-items-center justify-content-center">
    <div class="col-md-7">
    <h3><strong>Login in</strong></h3>
    <p class="mb-4">Please enter below Username and Password.</p>
    <form action="{% url 'core:login' %}" method="post">
        {% csrf_token %}
    <div class="form-group first">
        <div class="input-group mb-3">
            <div class="input-group-append mr-2">
                <span class=""><i class="fas fa-user mt-3"></i></span>
            </div>
            <input type="text"
               class="form-control ml-2"
               name="{{ login_form.username.name }}"
               placeholder="{{ login_form.username.label }}"
               id="{{ login_form.username.id_for_label }}"
               {% if login_form.username.value != None %}value="{{ login_form.username.value|stringformat:'s' }}"{% endif %}
               maxlength="{{ login_form.username.field.max_length }}"
               {% if login_form.username.field.required %}required{% endif %}>
        </div>
    </div>
    <div class="form-group last mb-3">
        <div class="input-group mb-4">
            <div class="input-group-append">
                <span class=""><i class="fa fa-asterisk mt-3"></i></span>
            </div>
            <input type="password"
               class="form-control ml-3"
               name="{{ login_form.password.name }}"
               placeholder="{{ login_form.password.label }}"
               id="{{ login_form.password.id_for_label }}"
               {% if login_form.password.value != None %}value="{{ login_form.password.value|stringformat:'s' }}"{% endif %}
               maxlength="{{ login_form.password.field.max_length }}"
               {% if login_form.password.field.required %}required{% endif %}>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-6">
            <button type="submit" class="btn btn-primary btn-lg"><i class="fas fa-arrow-circle-right mr-2"></i>Login</button>
        </div>
    </div>
    <div class="row">
        {% if login_form.errors %}
        <div class="alert alert-danger col-11 mt-3 ml-4" role="alert">
            Wrong username or password
        </div>
        {% endif %}
    </div>
    </form>

    <div>
        <p class="mt-4">Register now, it's free. <a href="{% url 'register:new-user' %}" class="active mt-3" >Register Now!<i class="fas fa-user-plus ml-2"></i></a></p>
    </div>

    </div>
    </div>
    </div>
    </div>
    </div>


<!-- Bootstrap and necessary plugins -->
<script src="{% static 'core/vendors/js/jquery.min.js'%}"></script>
<script src="{% static 'core/vendors/js/popper.min.js'%}"></script>
<script src="{% static 'core/vendors/js/bootstrap.min.js'%}"></script>
<script src="{% static 'core/vendors/js/pace.min.js'%}"></script>
<script src="{% static 'core/vendors/js/Chart.min.js'%}"></script>

<!-- CoreUI main scripts -->

<script src="{% static 'core/js/app.js'%}"></script>

<!-- Plugins and scripts required by this views -->

<!-- Custom scripts required by this view -->
<script src="{% static 'core/js/main.js'%}"></script>




<script src="js/jquery-3.3.1.min.js"></script>
<script src="js/popper.min.js+bootstrap.min.js+main.js.pagespeed.jc.knpfk1Gqze.js"></script>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='{"rayId":"6768b69e8f52d22c","token":"cd0b4b3a733644fc843ef0b185f98241","version":"2021.7.0","si":10}'></script>
</body>
{% endblock body%}



</html>

core/templates/core/sign-up.html
{% load static%}
<!doctype html>
<html lang="en">
<head>
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-147225311-2"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-147225311-2');
    </script>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="CoreUI - Open Source Bootstrap Admin Template">
  <meta name="author" content="Batuhan Sakarya">
  <meta name="keyword" content="Bootstrap,Admin,Template,Open,Source,AngularJS,Angular,Angular2,Angular 2,Angular4,Angular 4,jQuery,CSS,HTML,RWD,Dashboard,React,React.js,Vue,Vue.js">
  <meta name="google-site-verification" content="83fcqoPn-YTkXathQiicW-x3U2RWZh4PaPUzk91wtjY" />
  <title>Sign up</title>
  <link rel="shortcut icon" href="{% static 'core/img/logos/logo4.svg' %}">

  <!-- Icons -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.9/css/all.css" integrity="sha384-5SOiIsAziJl6AWe0HWRKTXlfcSHKmYV4RBF18PPJ173Kzn7jzMyFuTtk8JA7QQG1" crossorigin="anonymous">
  <link href="{% static 'core/css/simple-line-icons.min.css' %}" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">

  <!-- Main styles for this application -->
  <link rel="stylesheet" href="{% static 'core/css/login.css' %}">
</head>
<body>
    
    {% block body %}

    <div class="d-lg-flex half">
        <div class="bg order-1 order-md-2" style="overflow: hidden;"><img src="https://picsum.photos/id/1/1000/955"></div>
    <div class="contents order-2 order-md-1">
    <div class="container">
    <div class="row align-items-center justify-content-center">
    <div class="col-md-7">
    <h3><strong>Sign Up</strong></h3>
    <p class="mb-4">Please enter below informations for register</p>
    <form method="POST" action="">
        {% csrf_token %}
        <div class="form-group first">
            <div class="input-group">
                {{ form.username }}
                <div class="input-group-append">
                    <span class=""><i class="fa fa-user ml-2 mt-3"></i></span>
                </div>
                {% if form.username.errors %}
                    <ol>
                    {% for error in form.username.errors %}
                        <li><strong>{{ error|escape }}</strong></li>
                    {% endfor %}
                    </ol>
                {% endif %}
            </div>
        </div>
    <div class="form-group">
        <div class="input-group">
            {{ form.first_name }}
            <div class="input-group-append">
                <span class=""><i class="fa fa-user ml-2 mt-3"></i></span>
            </div>
            {% if form.first_name.errors %}
                <ol>
                {% for error in form.first_name.errors %}
                    <li><strong>{{ error|escape }}</strong></li>
                {% endfor %}
                </ol>
            {% endif %}
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
            {{ form.last_name }}
            <div class="input-group-append">
                <span class=""><i class="fa fa-user ml-2 mt-3"></i></span>
            </div>
            {% if form.last_name.errors %}
                <ol>
                {% for error in form.last_name.errors %}
                    <li><strong>{{ error|escape }}</strong></li>
                {% endfor %}
                </ol>
            {% endif %}
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
            {{ form.email }}
            <div class="input-group-append">
                <span class=""><i class="fa fa-envelope ml-2 mt-3"></i></span>
            </div>
            {% if form.email.errors %}
                <ol>
                {% for error in form.email.errors %}
                    <li><strong>{{ error|escape }}</strong></li>
                {% endfor %}
                </ol>
            {% endif %}
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
            {{ form.password1 }}
            <div class="input-group-append">
                <span class=""><i class="fa fa-key ml-2 mt-3"></i></span>
            </div>
            {% if form.password1.errors %}
                <ol>
                {% for error in form.password1.errors %}
                    <li><strong>{{ error|escape }}</strong></li>
                {% endfor %}
                </ol>
            {% endif %}
        </div>
    </div>
    <div class="form-group">
        <div class="input-group">
            {{ form.password2 }}
            <div class="input-group-append">
                <span class=""><i class="fa fa-key ml-2 mt-3"></i></span>
            </div>

        </div>
        {% if form.password2.errors %}
                <ol>
                {% for error in form.password2.errors %}
                    <li><strong>{{ error|escape }}</strong></li>
                {% endfor %}
                </ol>
            {% endif %}
    </div>
    <div class="form-group last">
        <div class="input-group">
            {{ form.company }}
            <div class="input-group-append">
                <span class=""><i class="fa fa-industry ml-2 mt-3"></i></span>
            </div>
            {% if form.company.errors %}
                <ol>
                {% for error in form.company.errors %}
                    <li><strong>{{ error|escape }}</strong></li>
                {% endfor %}
                </ol>
            {% endif %}
        </div>
    </div>
    <div class="form-button mt-3">
        <button type="submit" class="btn btn-primary btn-lg" style="border-radius: 5px;"><i class="far fa-paper-plane"></i> Submit</button>
        <button type="reset" class="btn btn-danger btn-lg" style="border-radius: 5px;"><i class="fa fa-ban"></i> Reset</button>
    </div>
    </form>
    {{ form.errors }}
    </div>

    </div>
    </div>
    </div>
    </div>
    </div>


    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="js/main.js"></script>
    
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
    
      gtag('config', 'UA-23581568-13');
    </script>
    <script defer src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='{"rayId":"67649d746adb1c2b","token":"cd0b4b3a733644fc843ef0b185f98241","version":"2021.7.0","si":10}'></script>




    
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="js/main.js"></script>
    
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
    
      gtag('config', 'UA-23581568-13');
    </script>
    <script defer src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='{"rayId":"67649d746adb1c2b","token":"cd0b4b3a733644fc843ef0b185f98241","version":"2021.7.0","si":10}'></script>


<!-- Bootstrap and necessary plugins -->
<script src="{% static 'core/vendors/js/jquery.min.js'%}"></script>
<script src="{% static 'core/vendors/js/popper.min.js'%}"></script>
<script src="{% static 'core/vendors/js/bootstrap.min.js'%}"></script>
<script src="{% static 'core/vendors/js/pace.min.js'%}"></script>
<script src="{% static 'core/vendors/js/Chart.min.js'%}"></script>

<!-- CoreUI main scripts -->

<script src="{% static 'core/js/app.js'%}"></script>

<!-- Plugins and scripts required by this views -->

<!-- Custom scripts required by this view -->
<script src="{% static 'core/js/main.js'%}"></script>

</body>
{% endblock body %}

</html>